### ISSUE TITLE
Background running?

### ISSUE THREAD

**Issue by vishalhify13** [drbergeron/wsb_synth_pub#14]
If my phone gets lock it stop working( s21, max cellphone stay unlock for 10 min). Can you do some so it work even if I lock my phone like you tube, YouTube music , Spotify etc. Thanks

**Comment by vishalhify13** [comment]
I can manage to do by my self. Thx

**Comment by drbergeron** [comment]
Very device specific, but until apps are granted some sort of ability to run javascript in the background, the issue isn't with the speech it's with chrome freezing javascript (which this uses to run).

https://stackoverflow.com/questions/64022061/html5-website-running-geolocation-and-audio-output-while-phone-screen-is-off

The only true fix might be an App (vs chrome)
